project/apps/core/urls.py
from django.conf.urls import patterns, url
from project.apps.core.views import BuildsList, BuildDetail, BuildAdd, IndexPage, BuildVote, FAQPage


urlpatterns = patterns(
    'core.views',
    url(r'^$', IndexPage.as_view(), name='index'),
    url(r'^list/$', BuildsList.as_view(), {}, name='builds_list'),
    url(r'^list/(?P<optional>.*)/$', BuildsList.as_view(), {}, name='builds_list'),
    url(r'^(?P<pk>\d+)/$', BuildDetail.as_view(), name='build_detail'),
    url(r'^vote/$', BuildVote.as_view(), name='build_vote'),
    url(r'^add/$', BuildAdd.as_view(), name='build_add'),

    url(r'^faq/$', FAQPage.as_view(), name='faq'),

)

project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 3rd-party apps
urlpatterns += patterns(
    '',
    # url('^markdown/', include('django_markdown.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

# Project apps
urlpatterns += patterns(
    '',
    url(r'^', include(u'core.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
        url(r'^500/$', TemplateView.as_view(template_name='500.html')),
    )

# Staticfiles
urlpatterns += staticfiles_urlpatterns()

project/apps/core/models.py
# coding: utf-8
import re
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings


class PublishedBuildManager(models.Manager):
    def get_queryset(self):
        return super(PublishedBuildManager, self).get_queryset().filter(published=True)


class Build(models.Model):
    BARBARIAN = 0
    CRUSADER = 1
    DEMON_HUNTER = 2
    MONK = 3
    WITCH_DOCTOR = 4
    WIZARD = 5

    HERO_CLASSES = (
        (BARBARIAN, u'Варвар'),
        (CRUSADER, u'Крестоносец'),
        (DEMON_HUNTER, u'Охотник на демонов'),
        (MONK, u'Монах'),
        (WITCH_DOCTOR, u'Колдун'),
        (WIZARD, u'Чародей'),
    )

    author = models.CharField(u'Автор', help_text=u'Можно указать свой BattleTag', max_length=255, default=u'Гость')
    email = models.EmailField('Электронная почта', max_length=255, help_text=u'Не будет отображаться на сайте')
    name = models.CharField(u'Название билда', max_length=255)
    hero_class = models.IntegerField(u'Класс', choices=HERO_CLASSES, default=BARBARIAN)
    calculator_url = models.URLField(u'Ссылка на калькулятор Blizzard', max_length=255)
    profile_url = models.URLField(u'Ссылка на профиль Blizzard', max_length=255, blank=True, null=True)
    # diablo_version = models.CharField(u'Версия игры', max_length=255, default=u'2.0.4')
    diablo_version = models.ForeignKey(u'Version', verbose_name=u'Версия игры', blank=True, null=True)
    description = models.TextField(u'Описание',
                                   help_text=u'Доступна markdown-разметка ('
                                   u'<a href="http://daringfireball.net/projects/markdown/syntax" '
                                   u'rel="nofollow" target="_blank">описание</a>)'
                                   )
    youtube = models.URLField(u'Видео работы билда на youtube', max_length=255, blank=True, null=True,
                              help_text=u'Пример ссылки: http://www.youtube.com/watch?v=juT-1ew-ffc')
    rating = models.IntegerField(u'Рейтинг', default=0)

    published = models.BooleanField(u'Опубликован', default=False)

    date_created = models.DateTimeField(u'Дата создания', auto_now_add=True)

    objects = models.Manager()
    published_objects = PublishedBuildManager()

    class Meta:
        verbose_name = u'Билд'
        verbose_name_plural = u'Билды'
        # ordering = (u'-rating', u'-id')
        ordering = (u'-diablo_version', u'-rating')

    def get_absolute_url(self):
        return reverse(u'build_detail', args=(self.id,))

    def get_youtube_embed(self):
        match = re.search(r'^(http|https)\:\/\/www\.youtube\.com\/watch\?v\=(\w*)(\&(.*))?$', self.youtube)
        if match:
            url = u'http://www.youtube.com/embed/%s' % (match.group(2))
            embed = u'<iframe width="560" height="315" src="%s" frameborder="0" allowfullscreen></iframe>' % url
            return embed
        return None

    def get_hero_class_slug(self):
        slugs = {
            0: u'barbarian',
            1: u'crusader',
            2: u'demonhunter',
            3: u'monk',
            4: u'witchdoctor',
            5: u'wizard',
        }
        return slugs[self.hero_class]

    def get_hero_class_icon(self):
        return settings.STATIC_URL + u'img/heroes/%s.png' % self.get_hero_class_slug()

    def rate_up(self):
        self.rating += 1
        self.save()

    def rate_down(self):
        self.rating -= 1
        self.save()

    def __unicode__(self):
        return self.name


class Guest(models.Model):
    ip = models.CharField(u'ip-адрес', max_length=255, default=0)
    rated_builds = models.ManyToManyField(Build, through=u'Vote', verbose_name=u'Оцененные билды', blank=True, null=True)

    path = models.CharField(u'Последний запрос', max_length=255, null=True, blank=True)
    referer = models.TextField(u'Последний Referer', null=True, blank=True)
    user_agent = models.TextField(u'Последний User Agent', null=True, blank=True)

    date_created = models.DateTimeField(u'Дата создания', auto_now_add=True)
    date_modified = models.DateTimeField(u'Дата изменения', auto_now=True)

    class Meta:
        verbose_name = u'Гость'
        verbose_name_plural = u'Гости'
        ordering = (u'ip',)

    def __unicode__(self):
        return self.ip


class Vote(models.Model):
    DOWN = 0
    UP = 1

    VOTE_CHOICES = (
        (DOWN, u'Вниз'),
        (UP, u'Вверх'),
    )
    build = models.ForeignKey(Build, verbose_name=u'Билд')
    guest = models.ForeignKey(Guest, verbose_name=u'Гость')
    action = models.IntegerField(u'Голос', choices=VOTE_CHOICES, default=0)
    date_voted = models.DateField(u'Дата последнего голоса', auto_now=True)

    class Meta:
        verbose_name = u'Голос'
        verbose_name_plural = u'Голоса'

    def __unicode__(self):
        return u'%s за %s' % (self.guest, self.build)


class News(models.Model):
    title = models.CharField(u'Заголовок', max_length=255, blank=True, null=True)
    text = models.TextField(u'Текст', blank=True, null=True)
    date_created = models.DateTimeField(u'Дата создания', default=datetime.now())

    class Meta:
        ordering = (u'-id',)
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'

    def __unicode__(self):
        return self.title


class Version(models.Model):
    name = models.CharField(u'Версия', max_length=255, default=u'2.1.0')

    class Meta:
        verbose_name = u'Версия игры'
        verbose_name_plural = u'Версии игры'

    def __unicode__(self):
        return self.name


class FAQ(models.Model):
    question = models.CharField(u'Вопрос', max_length=255)
    answer = models.CharField(u'Ответ', max_length=255)

    class Meta:
        verbose_name = u'FAQ'
        verbose_name_plural = u'FAQ'

    def __unicode__(self):
        return u'Q: {q}\n{a}'.format(q=self.question, a=self.answer)

project/apps/core/forms.py
# coding: utf-8
from urlparse import urlparse
from django import forms

from ckeditor.widgets import CKEditorWidget

from project.apps.core.models import Build


class CreateForm(forms.ModelForm):
    def clean_calculator_url(self):
        url = urlparse(self.cleaned_data[u'calculator_url'])
        valid_domain = u'eu.battle.net'
        if not url.netloc == valid_domain:
            raise forms.ValidationError(u'Введите ссылку на калькулятор от Blizzard')
        return self.cleaned_data[u'calculator_url']

    def clean_profile_url(self):
        url = urlparse(self.cleaned_data[u'profile_url'])
        valid_domain = u'eu.battle.net'
        if url.netloc and not url.netloc == valid_domain:
            raise forms.ValidationError(u'Введите ссылку на профиль на сайте Blizzard')
        return self.cleaned_data[u'profile_url']

    def clean_youtube(self):
        url = urlparse(self.cleaned_data[u'youtube'])
        valid_domain = u'youtube.com'
        if url.netloc and not url.netloc == valid_domain:
            raise forms.ValidationError(u'Введите ссылку на ролик на Youtube')
        return self.cleaned_data[u'youtube']

    email = forms.EmailField(
        widget=forms.TextInput(attrs={u'class': u'form-control', u'type': 'email'}),
        error_messages={'invalid': u'Пожалуйста, введите корректный e-mail адрес.'}
    )

    class Meta:
        model = Build
        exclude = (u'published', u'diablo_version', u'rating',)
        widgets = {
            u'author': forms.TextInput(attrs={u'class': u'form-control'}),
            u'name': forms.TextInput(attrs={u'class': u'form-control'}),
            u'hero_class': forms.Select(attrs={u'class': u'form-control'}),
            u'calculator_url': forms.TextInput(attrs={u'class': u'form-control'}),
            u'profile_url': forms.TextInput(attrs={u'class': u'form-control'}),
            u'description': CKEditorWidget(attrs={u'cols': 50, u'class': u'form-control'}),
            u'youtube': forms.TextInput(attrs={u'class': u'form-control'}),
        }

project/apps/core/views.py
# coding: utf-8
from datetime import datetime
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, View, TemplateView
from rebranch_shortcuts.django.models import get_object_or_none
from rebranch_shortcuts.django.views import JSONResponseMixin
from project.apps.core.forms import CreateForm
from project.apps.core.models import Build, Guest, Vote, FAQ


class IndexPage(ListView):
    template_name = u'index.html'
    model = Build
    context_object_name = u'builds'

    def get_queryset(self):
        return self.model.published_objects.all()


class BuildsList(ListView):
    template_name = u'list.html'
    model = Build
    context_object_name = u'builds'

    HERO_CLASSES = {
        u'barbarian': 0,
        u'crusader': 1,
        u'demonhunter': 2,
        u'monk': 3,
        u'witchdoctor': 4,
        u'wizard': 5,
    }

    SORT_PARAMS = (u'date_created', u'rating')

    def __init__(self, **kwargs):
        super(BuildsList, self).__init__(**kwargs)
        self.query = {}

    def get_queryset(self):
        sort = self.request.GET.get(u'sort', None)
        hero_class = self.kwargs.get(u'optional', None)
        if hero_class and hero_class in self.HERO_CLASSES.keys():
            self.query[u'hero_class'] = self.HERO_CLASSES[hero_class]
        builds = self.model.published_objects.filter(**self.query)
        if sort and sort in self.SORT_PARAMS:
            builds = reversed(builds.order_by(sort))
        return builds


class BuildDetail(DetailView):
    template_name = u'detail.html'
    model = Build
    context_object_name = u'build'


class BuildVote(View, JSONResponseMixin):
    def post(self, request, *args, **kwargs):
        build_id = request.POST.get(u'id', u'')

        ip = request.META.get('HTTP_X_FORWARDED_FOR', '') or request.META.get('REMOTE_ADDR', '')
        path = request.META.get('PATH_INFO')
        user_agent = request.META.get('HTTP_USER_AGENT')
        referer = request.META.get('HTTP_REFERER')

        build = get_object_or_none(Build, id=build_id)

        action_param = request.POST.get(u'action', u'')
        if action_param == u'up':
            action = 1
        elif action_param == u'down':
            action = 0
        else:
            action = None

        if not build or action is None:
            return self.render_to_json_response(status=self.response_status.fail)

        guest, _ = Guest.objects.get_or_create(
            ip=ip,
            # defaults={
            #     u'user_agent': user_agent,
            #     u'referrer': referrer,
            #     u'path': path,
            # }
        )
        guest.user_agent = user_agent
        guest.referer = referer
        guest.path = path
        guest.save()

        vote, created = Vote.objects.get_or_create(
            date_voted=datetime.now(),
            build=build,
            guest=guest,
            defaults={
                u'action': action
            }
        )

        if not created:
            return self.render_to_json_response(
                status=self.response_status.fail,
                data={u'error': u'Вы уже голосовали за этот билд сегодня.'}
            )

        if action == 1:
            build.rate_up()
        elif action == 0:
            build.rate_down()
        else:
            return self.render_to_json_response(status=self.response_status.fail)

        data = {
            u'rating': build.rating
        }
        return self.render_to_json_response(status=self.response_status.success, data=data)


class BuildAdd(CreateView):
    template_name = u'add.html'
    form_class = CreateForm

    def get_success_url(self):
        return reverse(u'index')

    def form_valid(self, form):
        build = Build.objects.create(**form.cleaned_data)
        messages.success(self.request, u'Билд успешно добавлен на модерацию.')
        send_mail(
            u'Новый билд',
            u'На сайте появился новый билд под названием %s' % build.name,
            u'mail@diablobuilds.ru', [u'fly.amureki@gmail.com']
        )
        return HttpResponseRedirect(self.get_success_url())


class FAQPage(ListView):
    template_name = u'faq.html'
    model = FAQ
    context_object_name = 'faq_list'

project/templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Добавление билда
{% endblock title %}

{% block nav-build-add %}active{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Добавление билда
            <small></small>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ form.media }}
                        <p class="help-block">
                            {{ field.help_text|safe }}
                        </p>
                    </div>
                    {% for error in field.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endfor %}
                <hr/>
                <button type="submit" class="btn btn-default">Добавить</button>
            </form>
            <br/>
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% include 'sidebar.html' %}
        </div>
    </div>
{% endblock content %}

project/templates/adsense.html
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- diablobuilds -->
<ins class="adsbygoogle"
     style="display:inline-block;width:336px;height:280px"
     data-ad-client="ca-pub-3068769662998983"
     data-ad-slot="4248341066"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

project/templates/detail.html
{% extends 'base.html' %}
{% load core_extras %}

{% block title %}
    {{ build.name }}
{% endblock title %}

{% block nav-builds %}active{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Билды Diablo 3
            <small></small>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            <div class="row">
                <h2>{{ build.name }}</h2>

                <div id="{{ build.id }}" class="alert alert-info" hidden="hidden">
                    <button type="button" class="close" data-hide="alert" aria-hidden="true">&times;</button>
                    Вы уже голосовали за этот билд сегодня.
                </div>

                <p class="pull-left">{{ build.date_created|date:"DATE_FORMAT" }}, автор:
{#                    {% if build.author != 'Гость' %}#}
                    {% if build.author != 'Гость' and build.author|battletag != None %}
                        {{ build.author|battletag|safe }}
                    {% else %}
                        {{ build.author }}
                    {% endif %}
                </p>

                <p class="pull-right rating" id="{{ build.id }}">
                    {% csrf_token %}
                    Класс: <a href="#">{{ build.get_hero_class_display }}</a>
                    | Рейтинг:
                    <button id="down" data-value="down" class="btn-link"><strong>-</strong></button>
                    <span class="rating" id="{{ build.id }}">{{ build.rating }}</span>
                    <button id="up" data-value="up" class="btn-link"><strong>+</strong></button>
                </p>
                <br><br>

                <p><a href="{{ build.calculator_url }}">Ссылка на калькулятор</a></p>
                <hr>

                <p>{{ build.description|safe }}</p>
                {% if build.get_youtube_embed %}
                <p>Пример работы билда:</p>
                {{ build.get_youtube_embed|safe }}
                {% endif %}
                <hr>
                {% load disqus_tags %}
                {% disqus_dev %}
                {% disqus_show_comments %}
            </div>
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% include 'sidebar.html' %}
        </div>
    </div>
{% endblock content %}

project/templates/faq.html
{% extends 'base.html' %}

{% block title %}
    FAQ
{% endblock title %}

{% block nav-faq %}active{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>FAQ<small></small></h1>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            {% for faq_entry in faq_list %}
                <h3>Q: {{ faq_entry.question }}</h3><br/>

                <p>{% autoescape off %}{{ faq_entry.answer }}{% endautoescape %}</p>
                <hr/>

            {% empty %}

                Здесь пусто.

            {% endfor %}
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% include 'sidebar.html' %}
        </div>
    </div>
{% endblock content %}

project/templates/index.html
{% extends 'base.html' %}
{% load core_extras %}

{% block title %}
    Билды для Diablo 3
{% endblock title %}

{% block nav-index %}active{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Билды Diablo 3 <small></small></h1>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            {% for build in builds %}
                <div class="row">
                    <h2><a href="{{ build.get_absolute_url }}">{{ build.name }}</a> <small>{{ build.diablo_version|default:"" }}</small></h2>

                    <div id="{{ build.id }}" class="alert alert-info" hidden="hidden">
                        <button type="button" class="close" data-hide="alert" aria-hidden="true">&times;</button>
                        Вы уже голосовали за этот билд сегодня.
                    </div>

                    <p class="pull-left">{{ build.date_created|date:"DATE_FORMAT" }}, автор:
{#                        {% if build.author != 'Гость' %}#}
                        {% if build.author != 'Гость' and build.author|battletag != None %}
                            {{ build.author|battletag|safe }}
                        {% else %}
                            {{ build.author }}
                        {% endif %}
                    </p>

                    <p class="pull-right rating" id="{{ build.id }}">
                        {% csrf_token %}
                        Класс: <a href="{% url 'builds_list' build.get_hero_class_slug  %}"><span><img class="img-rounded" src="{{ build.get_hero_class_icon }}" height="26px"/></span>{{ build.get_hero_class_display }}</a>
                        | Рейтинг:
                        <button id="down" data-value="down" class="btn-link"><strong>-</strong></button>
                        <span class="rating" id="{{ build.id }}">{{ build.rating }}</span>
                        <button id="up" data-value="up" class="btn-link"><strong>+</strong></button>
                    </p>
                    <br><br>

                    <p>
                        <a href="{{ build.calculator_url }}">Ссылка на калькулятор</a> |
                        <a href="{{ build.get_absolute_url }}">Читать &raquo;</a>
                    </p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% include 'sidebar.html' %}
        </div>
    </div>
{% endblock content %}

project/templates/list.html
{% extends 'base.html' %}
{% load core_extras %}

{% block title %}
    Список билдов
{% endblock title %}

{% block nav-builds %}active{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Список билдов
            <small></small>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-4 col-md-offset-1">
            <div class="row">
                <p>Сортировка по
                    <a href="{{ request.path }}?sort=date_created">дате</a> |
                    <a href="{{ request.path }}?sort=rating">рейтингу</a>
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            {% for build in builds %}
                <div class="row">
                    <h2><a href="{{ build.get_absolute_url }}">{{ build.name }}</a> <small>{{ build.diablo_version|default:"" }}</small></h2>

                    <div id="{{ build.id }}" class="alert alert-info" hidden="hidden">
                        <button type="button" class="close" data-hide="alert" aria-hidden="true">&times;</button>
                        Вы уже голосовали за этот билд сегодня.
                    </div>

                    <p class="pull-left">{{ build.date_created|date:"DATE_FORMAT" }}, автор:
{#                        {% if build.author != 'Гость' %}#}
                        {% if build.author != 'Гость' and build.author|battletag != None %}
                            {{ build.author|battletag|safe }}
                        {% else %}
                            {{ build.author }}
                        {% endif %}
                    </p>

                    <p class="pull-right rating" id="{{ build.id }}">
                        {% csrf_token %}
                        Класс: <a href="#"><span><img class="img-rounded" src="{{ build.get_hero_class_icon }}" height="26px"/></span>{{ build.get_hero_class_display }}</a>
                        | Рейтинг:
                        <button id="down" data-value="down" class="btn-link"><strong>-</strong></button>
                        <span class="rating" id="{{ build.id }}">{{ build.rating }}</span>
                        <button id="up" data-value="up" class="btn-link"><strong>+</strong></button>
                    </p>
                    <br><br>

                    <p><a href="{{ build.calculator_url }}">Ссылка на калькулятор</a></p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        <div class="col-md-3 col-md-offset-1">
            {% include 'sidebar.html' %}
        </div>
    </div>
{% endblock content %}

project/templates/sidebar.html
<div class="row">
    <h4>О проекте</h4>

    <p>Проект создан для составления рейтинга билдов <em>для актуальной на текущий момент версии игры</em> Diablo 3.
    </p>

    <p>Текущая версия игры: <strong>{{ config.CURRENT_GAME_VERSION }}</strong></p>
</div>

<div class="row">
    <h4>Новости</h4>
    <ol class="list-unstyled">
        {% for item in news %}
            <li>{{ item.text }}
                <small>({{ item.date_created|date:'SHORT_DATE_FORMAT' }})</small>
            </li>
            <br/>
        {% endfor %}
    </ol>
</div>

<div class="row">
    {% include 'adsense.html' %}
</div>